apiVersion: v1
kind: Secret
metadata:
  name: postgres-keycloak-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgresKeycloak.username | quote }}
  password: {{ .Values.postgresKeycloak.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgresApp.username | quote }}
  password: {{ .Values.postgresApp.password | quote }}
